/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ELI
 */
public class Ejercicio7 extends javax.swing.JFrame {
    
    String s;
    /**
     * Creates new form Ejercicio7
     */
    public Ejercicio7() {
        initComponents();
        s="";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiUno = new javax.swing.JLabel();
        etiDos = new javax.swing.JLabel();
        etiTres = new javax.swing.JLabel();
        etiCuatro = new javax.swing.JLabel();
        etiCinco = new javax.swing.JLabel();
        etiSeis = new javax.swing.JLabel();
        etiSiete = new javax.swing.JLabel();
        etiOcho = new javax.swing.JLabel();
        etiNueve = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        btnBorrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        etiUno.setBackground(new java.awt.Color(0, 0, 204));
        etiUno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiUno.setText("1");
        etiUno.setOpaque(true);
        etiUno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                etiUnoMouseEntered(evt);
            }
        });

        etiDos.setBackground(new java.awt.Color(0, 0, 255));
        etiDos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiDos.setText("2");
        etiDos.setOpaque(true);
        etiDos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                etiDosMouseEntered(evt);
            }
        });

        etiTres.setBackground(new java.awt.Color(0, 0, 255));
        etiTres.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiTres.setText("3");
        etiTres.setOpaque(true);
        etiTres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                etiTresMouseEntered(evt);
            }
        });

        etiCuatro.setBackground(new java.awt.Color(0, 0, 255));
        etiCuatro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiCuatro.setText("4");
        etiCuatro.setOpaque(true);
        etiCuatro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                etiCuatroMouseEntered(evt);
            }
        });

        etiCinco.setBackground(new java.awt.Color(0, 0, 255));
        etiCinco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiCinco.setText("5");
        etiCinco.setOpaque(true);
        etiCinco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                etiCincoMouseEntered(evt);
            }
        });

        etiSeis.setBackground(new java.awt.Color(0, 0, 255));
        etiSeis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiSeis.setText("6");
        etiSeis.setOpaque(true);
        etiSeis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                etiSeisMouseEntered(evt);
            }
        });

        etiSiete.setBackground(new java.awt.Color(0, 0, 255));
        etiSiete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiSiete.setText("7");
        etiSiete.setOpaque(true);
        etiSiete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                etiSieteMouseEntered(evt);
            }
        });

        etiOcho.setBackground(new java.awt.Color(0, 0, 255));
        etiOcho.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiOcho.setText("8");
        etiOcho.setOpaque(true);
        etiOcho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                etiOchoMouseEntered(evt);
            }
        });

        etiNueve.setBackground(new java.awt.Color(0, 0, 255));
        etiNueve.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiNueve.setText("9");
        etiNueve.setOpaque(true);
        etiNueve.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                etiNueveMouseEntered(evt);
            }
        });

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(etiUno, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                            .addComponent(etiDos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(etiTres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(etiCuatro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(etiCinco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(etiNueve, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, Short.MAX_VALUE)
                        .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(etiSiete, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(etiOcho, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(etiSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBorrar)
                        .addGap(89, 89, 89))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiUno)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(btnBorrar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(etiDos)
                        .addGap(18, 18, 18)
                        .addComponent(etiTres)
                        .addGap(18, 18, 18)
                        .addComponent(etiCuatro)
                        .addGap(18, 18, 18)
                        .addComponent(etiCinco)
                        .addGap(18, 18, 18)
                        .addComponent(etiSeis)))
                .addGap(18, 18, 18)
                .addComponent(etiSiete)
                .addGap(18, 18, 18)
                .addComponent(etiOcho)
                .addGap(18, 18, 18)
                .addComponent(etiNueve)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void etiUnoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiUnoMouseEntered
        s+=1;
        txtNumero.setText(s);
    }//GEN-LAST:event_etiUnoMouseEntered

    private void etiDosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiDosMouseEntered
        s+=2;
        txtNumero.setText(s);
    }//GEN-LAST:event_etiDosMouseEntered

    private void etiTresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiTresMouseEntered
        s+=3;
        txtNumero.setText(s);
    }//GEN-LAST:event_etiTresMouseEntered

    private void etiCuatroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiCuatroMouseEntered
        s+=4;
        txtNumero.setText(s);
    }//GEN-LAST:event_etiCuatroMouseEntered

    private void etiCincoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiCincoMouseEntered
        s+=5;
        txtNumero.setText(s);
    }//GEN-LAST:event_etiCincoMouseEntered

    private void etiSeisMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiSeisMouseEntered
        s+=6;
        txtNumero.setText(s);
    }//GEN-LAST:event_etiSeisMouseEntered

    private void etiSieteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiSieteMouseEntered
        s+=7;
        txtNumero.setText(s);
    }//GEN-LAST:event_etiSieteMouseEntered

    private void etiOchoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiOchoMouseEntered
        s+=8;
        txtNumero.setText(s);
    }//GEN-LAST:event_etiOchoMouseEntered

    private void etiNueveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiNueveMouseEntered
        s+=9;
        txtNumero.setText(s);
    }//GEN-LAST:event_etiNueveMouseEntered

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        s="";
        txtNumero.setText(s);
    }//GEN-LAST:event_btnBorrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio7().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JLabel etiCinco;
    private javax.swing.JLabel etiCuatro;
    private javax.swing.JLabel etiDos;
    private javax.swing.JLabel etiNueve;
    private javax.swing.JLabel etiOcho;
    private javax.swing.JLabel etiSeis;
    private javax.swing.JLabel etiSiete;
    private javax.swing.JLabel etiTres;
    private javax.swing.JLabel etiUno;
    private javax.swing.JTextField txtNumero;
    // End of variables declaration//GEN-END:variables
}
