/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ELI
 */
public class Ejercicio1 extends javax.swing.JFrame {

    /**
     * Creates new form Ejercicio1
     */
    public Ejercicio1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiNombre = new javax.swing.JLabel();
        etiCiudad = new javax.swing.JLabel();
        btnOcultarNombre = new javax.swing.JButton();
        btnOcultarCiudad = new javax.swing.JButton();
        btnVisualizarNombre = new javax.swing.JButton();
        btnVisualizarCiudad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        etiNombre.setText("Erwin Eli Parada Martinez");
        etiNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        etiCiudad.setText("Oaxaca de Juarez");
        etiCiudad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnOcultarNombre.setText("Ocultar Nombre");
        btnOcultarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOcultarNombreActionPerformed(evt);
            }
        });

        btnOcultarCiudad.setText("Ocultar Ciudad");
        btnOcultarCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOcultarCiudadActionPerformed(evt);
            }
        });

        btnVisualizarNombre.setText("VisualizarNombre");
        btnVisualizarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarNombreActionPerformed(evt);
            }
        });

        btnVisualizarCiudad.setText("Visualizar Ciudad");
        btnVisualizarCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarCiudadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnOcultarNombre)
                    .addComponent(btnVisualizarNombre)
                    .addComponent(etiNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVisualizarCiudad)
                    .addComponent(btnOcultarCiudad)
                    .addComponent(etiCiudad))
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiNombre)
                    .addComponent(etiCiudad))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOcultarNombre)
                    .addComponent(btnOcultarCiudad))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVisualizarNombre)
                    .addComponent(btnVisualizarCiudad))
                .addContainerGap(87, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOcultarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOcultarNombreActionPerformed
        etiNombre.setVisible(false);
    }//GEN-LAST:event_btnOcultarNombreActionPerformed

    private void btnVisualizarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarNombreActionPerformed
         etiNombre.setVisible(true);
    }//GEN-LAST:event_btnVisualizarNombreActionPerformed

    private void btnOcultarCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOcultarCiudadActionPerformed
        etiCiudad.setVisible(false);
    }//GEN-LAST:event_btnOcultarCiudadActionPerformed

    private void btnVisualizarCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarCiudadActionPerformed
        etiCiudad.setVisible(true);
    }//GEN-LAST:event_btnVisualizarCiudadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOcultarCiudad;
    private javax.swing.JButton btnOcultarNombre;
    private javax.swing.JButton btnVisualizarCiudad;
    private javax.swing.JButton btnVisualizarNombre;
    private javax.swing.JLabel etiCiudad;
    private javax.swing.JLabel etiNombre;
    // End of variables declaration//GEN-END:variables
}
