
import javax.swing.UIManager;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ELI
 */
public class EJ_LENGUAJE_JAVA_14 extends javax.swing.JFrame {

    /**
     * Creates new form EJ_LENGUAJE_JAVA_14
     */
    public EJ_LENGUAJE_JAVA_14() {
        initComponents();
        optPlano.setSelected(true);
        desFrecuencia1.setValue(5);
        desFrecuencia2.setValue(5);
        desFrecuencia3.setValue(5);
        desFrecuencia4.setValue(5);
        desFrecuencia5.setValue(5);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoEcualizacion = new javax.swing.ButtonGroup();
        etiFrecuencia1 = new javax.swing.JLabel();
        chkFrecuencia1 = new javax.swing.JCheckBox();
        chkFrecuencia2 = new javax.swing.JCheckBox();
        desFrecuencia2 = new javax.swing.JScrollBar();
        etiFrecuencia2 = new javax.swing.JLabel();
        chkFrecuencia3 = new javax.swing.JCheckBox();
        desFrecuencia3 = new javax.swing.JScrollBar();
        etiFrecuencia3 = new javax.swing.JLabel();
        chkFrecuencia4 = new javax.swing.JCheckBox();
        desFrecuencia4 = new javax.swing.JScrollBar();
        etiFrecuencia4 = new javax.swing.JLabel();
        chkFrecuencia5 = new javax.swing.JCheckBox();
        desFrecuencia5 = new javax.swing.JScrollBar();
        etiFrecuencia5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        optPelicula = new javax.swing.JRadioButton();
        opConcierto = new javax.swing.JRadioButton();
        optPlano = new javax.swing.JRadioButton();
        desFrecuencia1 = new javax.swing.JScrollBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        etiFrecuencia1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        chkFrecuencia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkFrecuencia1ActionPerformed(evt);
            }
        });

        chkFrecuencia2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkFrecuencia2ActionPerformed(evt);
            }
        });

        desFrecuencia2.setBlockIncrement(2);
        desFrecuencia2.setMaximum(11);
        desFrecuencia2.setValue(5);
        desFrecuencia2.setVisibleAmount(1);
        desFrecuencia2.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                desFrecuencia2AdjustmentValueChanged(evt);
            }
        });

        etiFrecuencia2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        chkFrecuencia3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkFrecuencia3ActionPerformed(evt);
            }
        });

        desFrecuencia3.setBlockIncrement(2);
        desFrecuencia3.setMaximum(11);
        desFrecuencia3.setValue(5);
        desFrecuencia3.setVisibleAmount(1);
        desFrecuencia3.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                desFrecuencia3AdjustmentValueChanged(evt);
            }
        });

        etiFrecuencia3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        chkFrecuencia4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkFrecuencia4ActionPerformed(evt);
            }
        });

        desFrecuencia4.setBlockIncrement(2);
        desFrecuencia4.setMaximum(11);
        desFrecuencia4.setValue(5);
        desFrecuencia4.setVisibleAmount(1);
        desFrecuencia4.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                desFrecuencia4AdjustmentValueChanged(evt);
            }
        });

        etiFrecuencia4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        chkFrecuencia5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkFrecuencia5ActionPerformed(evt);
            }
        });

        desFrecuencia5.setBlockIncrement(2);
        desFrecuencia5.setMaximum(11);
        desFrecuencia5.setValue(5);
        desFrecuencia5.setVisibleAmount(1);
        desFrecuencia5.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                desFrecuencia5AdjustmentValueChanged(evt);
            }
        });

        etiFrecuencia5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Ecualizaciones"));

        grupoEcualizacion.add(optPelicula);
        optPelicula.setText("Película");
        optPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optPeliculaActionPerformed(evt);
            }
        });

        grupoEcualizacion.add(opConcierto);
        opConcierto.setText("Concierto");
        opConcierto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opConciertoActionPerformed(evt);
            }
        });

        grupoEcualizacion.add(optPlano);
        optPlano.setText("Plano");
        optPlano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optPlanoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(optPelicula)
                    .addComponent(opConcierto)
                    .addComponent(optPlano))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(optPelicula)
                .addGap(18, 18, 18)
                .addComponent(opConcierto)
                .addGap(18, 18, 18)
                .addComponent(optPlano)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        desFrecuencia1.setBlockIncrement(2);
        desFrecuencia1.setMaximum(11);
        desFrecuencia1.setValue(5);
        desFrecuencia1.setVisibleAmount(1);
        desFrecuencia1.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                desFrecuencia1AdjustmentValueChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(etiFrecuencia1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(desFrecuencia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkFrecuencia1))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(chkFrecuencia2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(desFrecuencia2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(etiFrecuencia2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(chkFrecuencia3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(desFrecuencia3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(etiFrecuencia3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(chkFrecuencia4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(desFrecuencia4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(etiFrecuencia4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(chkFrecuencia5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(desFrecuencia5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(etiFrecuencia5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(etiFrecuencia5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(desFrecuencia5, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(chkFrecuencia5))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(etiFrecuencia4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(desFrecuencia4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(chkFrecuencia4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(etiFrecuencia3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(desFrecuencia3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(chkFrecuencia3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(etiFrecuencia2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(desFrecuencia2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(chkFrecuencia2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(etiFrecuencia1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(desFrecuencia1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(chkFrecuencia1)))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //hay un cambio de valores con respecto a 10 debido a que abajo es 10 y arriba es 0 por tanto se ve extranio asi que para eso se resta el valor a 10
    private void optPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optPeliculaActionPerformed
        desFrecuencia1.setValue(8);
        desFrecuencia2.setValue(5);
        desFrecuencia3.setValue(2);
        desFrecuencia4.setValue(5);
        desFrecuencia5.setValue(8);
    }//GEN-LAST:event_optPeliculaActionPerformed

    private void opConciertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opConciertoActionPerformed
        desFrecuencia1.setValue(1);
        desFrecuencia2.setValue(5);
        desFrecuencia3.setValue(9);
        desFrecuencia4.setValue(5);
        desFrecuencia5.setValue(1);
    }//GEN-LAST:event_opConciertoActionPerformed

    private void optPlanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optPlanoActionPerformed
        desFrecuencia1.setValue(5);
        desFrecuencia2.setValue(5);
        desFrecuencia3.setValue(5);
        desFrecuencia4.setValue(5);
        desFrecuencia5.setValue(5);
    }//GEN-LAST:event_optPlanoActionPerformed

    private void chkFrecuencia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkFrecuencia1ActionPerformed
        desFrecuencia1.setEnabled(!desFrecuencia1.isEnabled());
    }//GEN-LAST:event_chkFrecuencia1ActionPerformed

    private void chkFrecuencia2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkFrecuencia2ActionPerformed
        desFrecuencia2.setEnabled(!desFrecuencia2.isEnabled());
    }//GEN-LAST:event_chkFrecuencia2ActionPerformed

    private void chkFrecuencia3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkFrecuencia3ActionPerformed
        desFrecuencia3.setEnabled(!desFrecuencia3.isEnabled());
    }//GEN-LAST:event_chkFrecuencia3ActionPerformed

    private void chkFrecuencia4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkFrecuencia4ActionPerformed
        desFrecuencia4.setEnabled(!desFrecuencia4.isEnabled());
    }//GEN-LAST:event_chkFrecuencia4ActionPerformed

    private void chkFrecuencia5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkFrecuencia5ActionPerformed
        desFrecuencia5.setEnabled(!desFrecuencia5.isEnabled());
    }//GEN-LAST:event_chkFrecuencia5ActionPerformed

    private void desFrecuencia1AdjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_desFrecuencia1AdjustmentValueChanged
        etiFrecuencia1.setText(""+(10-desFrecuencia1.getValue()));
    }//GEN-LAST:event_desFrecuencia1AdjustmentValueChanged

    private void desFrecuencia2AdjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_desFrecuencia2AdjustmentValueChanged
        etiFrecuencia2.setText(""+(10-desFrecuencia2.getValue()));
    }//GEN-LAST:event_desFrecuencia2AdjustmentValueChanged

    private void desFrecuencia3AdjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_desFrecuencia3AdjustmentValueChanged
       etiFrecuencia3.setText(""+(10-desFrecuencia3.getValue()));
    }//GEN-LAST:event_desFrecuencia3AdjustmentValueChanged

    private void desFrecuencia4AdjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_desFrecuencia4AdjustmentValueChanged
        etiFrecuencia4.setText(""+(10-desFrecuencia4.getValue()));
    }//GEN-LAST:event_desFrecuencia4AdjustmentValueChanged

    private void desFrecuencia5AdjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_desFrecuencia5AdjustmentValueChanged
        etiFrecuencia5.setText(""+(10-desFrecuencia5.getValue()));
    }//GEN-LAST:event_desFrecuencia5AdjustmentValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EJ_LENGUAJE_JAVA_14.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EJ_LENGUAJE_JAVA_14.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EJ_LENGUAJE_JAVA_14.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EJ_LENGUAJE_JAVA_14.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EJ_LENGUAJE_JAVA_14().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkFrecuencia1;
    private javax.swing.JCheckBox chkFrecuencia2;
    private javax.swing.JCheckBox chkFrecuencia3;
    private javax.swing.JCheckBox chkFrecuencia4;
    private javax.swing.JCheckBox chkFrecuencia5;
    private javax.swing.JScrollBar desFrecuencia1;
    private javax.swing.JScrollBar desFrecuencia2;
    private javax.swing.JScrollBar desFrecuencia3;
    private javax.swing.JScrollBar desFrecuencia4;
    private javax.swing.JScrollBar desFrecuencia5;
    private javax.swing.JLabel etiFrecuencia1;
    private javax.swing.JLabel etiFrecuencia2;
    private javax.swing.JLabel etiFrecuencia3;
    private javax.swing.JLabel etiFrecuencia4;
    private javax.swing.JLabel etiFrecuencia5;
    private javax.swing.ButtonGroup grupoEcualizacion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton opConcierto;
    private javax.swing.JRadioButton optPelicula;
    private javax.swing.JRadioButton optPlano;
    // End of variables declaration//GEN-END:variables
}
